version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 15
    labels:
      - "changelog/ignore"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 15
    labels:
      - "changelog/dependencies"
